name: yologtest05
description: "Yolog."

publish_to:


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
    # Firebase 패키지들
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4  # Firebase Storage 사용 시 필요
  flutter_local_notifications: ^18.0.0

    # Flutter 관련 패키지들
  provider: ^6.1.2  # 상태 관리를 위해 사용
  cupertino_icons: ^1.0.8

    # 이미지 업로드 및 처리를 위한 패키지
  image_picker: ^1.1.2
  file_picker: ^8.1.3  # 파일 선택을 위한 패키지

    # 기타 유틸리티 패키지
  intl: ^0.19.0 # 날짜 포맷팅 등 유틸리티
  shared_preferences: ^2.3.2 # 로컬 저장소

    # UI 관련 패키지
  flutter_svg: ^2.0.13  # SVG 이미지 사용 시 필요

  flutter_riverpod: ^2.1.3  # 최신 버전 확인하고 추가



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0




flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  assets:
    - assets/fonts/
    - assets/images/google_logo.png
  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/Poppins-Regular.ttf
         - asset: assets/fonts/Poppins-Bold.ttf
           weight: 700
         - asset: assets/fonts/Poppins-Italic.ttf
           style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
